class Foreman::Export::Initd < Foreman::Export::Base

  def export
    error('Must specify a location') unless location

    cwd = Pathname.new(engine.root)
    export_to = Pathname.new(location)

    existing = []
    Dir.glob export_to.join("#{app}-*") do |filename|
      contents = File.new(filename, 'r').read
      existing.push(filename) if contents.match(/# Autogenerated by foreman/)
    end

    exported = []
    engine.each_process do |name, process|
      path = export_to.join("#{app}-#{name}")
      args = process.command.split(/\s+/)
      script = Pathname.new(cwd).join(args.shift)
      concurrency = engine.formation[name]
      if concurrency > 0
        say 'Warning: Initd exporter ignores concurrency > 1' if concurrency > 1
        initscript = Initd::Script.new path, script, args, user
        say 'Exporting ' + path.to_s
        initscript.export
        exported.push path.to_s
      end
    end

    to_remove = existing - exported
    to_remove.each do |filename|
      say 'Removing ' + filename
      File.unlink filename
    end
  end
end
